name: simpson_viewer
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  autoequal: ^0.5.1
  bloc: ^8.1.2
  copy_with_extension: ^5.0.3
  equatable: ^2.0.5
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_flavor: ^3.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^11.1.2
  go_router_paths: ^0.2.0
  http: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  mockito: ^5.4.2
  searchable_listview: ^2.4.0
  shimmer_animation: ^2.1.0+1

dev_dependencies:
  autoequal_gen: ^0.8.0
  bloc_test: ^9.1.2
  build_runner: ^2.1.7
  copy_with_extension_gen: ^5.0.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  meta: ^1.9.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - test/assets/

scripts: derry.yaml
